### ISSUE TITLE
Unable to find job from id

### ISSUE THREAD

**Issue by JonathanSerafini** [UpHabit/bull_exporter#212]
I've deployed Bull Exporter in Kubernetes to monitor our bull queue.

So far, it's able to report active, waiting and failed jobs however it does not appear to be able to get duration information. Tailing the pod logs indicates a constant influx of log messages indicating : 
`"level":40,"job":"2315963","msg":"unable to find job from id"`

Is there any insight you might be able to share in order to troubleshoot / resolve this issue ?

**Comment by Lp-Francois** [comment]
🆙 

Hello @JonathanSerafini,
Did you solve this issue?

I notice we encounter the same with our exporter
