### ISSUE TITLE
valid scrape_config example

### ISSUE THREAD

**Issue by rohithzr** [UpHabit/bull_exporter#214]
I have a prometheus-grafana setup on k8s and I have the bull pod running and it shows metrics at the /metrics endpoint and I have both scrape annotations at pod,deployment and service level.

Still on prometheus it doesnt show up, I believe I need to add a scrape config, can you assist me here?

**Comment by stamina11** [comment]
I have prometheus running in the same AKS clusters as Bulljs, here is what i have for my prometheus config. I hope this helps.
# ------------------------- Bull_Q_UAT -------------------------#
    - job_name: 'Bull_Q_UAT'
      static_configs:
          - targets:
              - 10.20.20.7:9999
            labels:
              Env: UAT
              Page: No
              Severity: 2

**Comment by rohithzr** [comment]
@stamina11 thanks this worked.
