### ISSUE TITLE
Where can I find the dashboard configuration for Grafana?

### ISSUE THREAD

**Issue by pavlovdog** [UpHabit/bull_exporter#61]
Hello guys!

Simple question - can you share the source for the Grafana dashboard which is presented in your README? Couldn't find it in the repo and in the [Grafana dashboards marketplace](https://grafana.com/dashboards?search=bull).

P.S. Thank you for your work - I was literally surprised when I found the well contributed and documented exporter for such rare queue as Bull.

**Comment by GabrielCastro** [comment]
Hi @pavlovdog,

Thanks for the interest, that dashboard is unfortunately very tied into one that has a lot more company data. I'll look into making a more generic that we can share soon.

**Comment by edijsdrezovs** [comment]
@GabrielCastro Can you share the one what you have in screenshot? Looks pretty much OK and useful.

**Comment by GabrielCastro** [comment]
Published here: https://grafana.com/dashboards/10128
