### ISSUE TITLE
Metrics per job

### ISSUE THREAD

**Issue by popovprodigyai** [UpHabit/bull_exporter#70]
Hi,
Is there any way to export metrics per job? Summary allows to have an overview of Avg execution time, but it would be great to see it on a job level.
Please advice!

**Comment by GabrielCastro** [comment]
No 100% sure what you're asking but:

If you want stats per queue (job type) you can filter with labels ie:
`bull_queue_complete_duration { quantile="0.999", queue="someJob" }` will get you the .999 p for just  jobs of type `someJob`

If you want something to query per specific job instance that's not something Prometheus is good at in general, we use [arena](https://github.com/bee-queue/arena) to dig into specific jobs

**Comment by popovprodigyai** [comment]
Sorry, did not see your reply before...
Here is the simple example:
- 1 queue;
- 2 jobs were ran in this queue:
a) Download docs - Job ID: 1; Job name: `download-doc`
b) Store docs - Job ID: 2; Job name: `store-doc`

So the point is - want to have stats based on Job Name. What you are proposing is based on Queue name.
