### ISSUE TITLE
Running bull_exporter

### ISSUE THREAD

**Issue by rvalim** [UpHabit/bull_exporter#93]
Hi guys,

I am trying to put it to run, I am using the command bellow:

- docker run --rm -p 3000:3000 uphabit/bull_exporter:latest: The container is Up, but I can't access to it
- docker run --rm -p 3000:3000 grafana/grafana:latest: Works fine

Am I missing something? Ok the Redis is not specified, but i tried to send env variable but even with nothing happend.

Tks
Ricardo

**Comment by ashkank83** [comment]
@rvalim did you find a solution? would you kindly share? I'm having the same issue.

**Comment by rvalim** [comment]
@ashkank83 The bull_exporter, as I understand, just give me the metrics, it is basically an enpoint with information, then you have to install Prometheus and Grafana and link all them together.

So...I decided to use [Arena](https://github.com/bee-queue/arena)

**Comment by GabrielCastro** [comment]
@rvalim Is correct, this exporter just provides metrics for [Prometheus](https://prometheus.io/docs/introduction/overview/) to scrape. 

Which requires a working Prometheus set up. We use both this project and Arena in production as they serve different purposes.
